
spark.connect.grpc.binding.host=0.0.0.0
spark.connect.grpc.binding.port=15002

--conf spark.sql.streaming.schemaInference=true
--conf spark.hadoop.fs.s3a.endpoint=http://minio:9000
--conf spark.hadoop.fs.s3a.path.style.access=true
--conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
--conf spark.hadoop.fs.s3a.access.key=${MINIO_ACCESS_KEY}
--conf spark.hadoop.fs.s3a.secret.key=${MINIO_SECRET_KEY}
--conf spark.hadoop.fs.s3a.aws.credentials.provider=org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
